# This code is part of Tergite
#
# (C) Copyright Chalmers Next Labs 2024
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.


# ------------------
# Meta configuration
# In this file, we define which configurations are going to be used
# This file should be part of any configuration package

# The path_prefix defines the relative path from the meta configuration where configuration files are stored
path_prefix = 'configs'


# ---
# Run-time related configurations
# ---
# run_config is all information related to the current run of the autocalibration
# This is e.g. the target node, qubits and couplers
run_config = 'run_config.toml'


# ---
# Instruments-related configuration
# ---
# cluster_config is what Q-BLOX needs to compile schedules on the hardware.
# It should be a file in json format, there is no default file
cluster_config = 'cluster_config.json'

# device_config contains the initial values for the device configuration.
device_config = 'device_config.toml'

# spi_config is the file to configure the wiring on the Q-BLOX Spi Rack.
# This is only necessary if you are running two-qubit calibrations.
# If you just want to run single-qubit calibrations, you can go without an SPI configuration.
spi_config = 'spi_config.toml'


# ---
# Calibration library related configuration
# ---
# NODE_CONFIG contains all values for the runtime of the program.
node_config = 'node_config.toml'

# USER_SAMPLESPACE gives the possibility to define custom samplespaces.
user_samplespace = 'user_samplespace.py'
