image: python:3.9

definitions:
  caches:
    poetry:
      key:
        files:
          - "poetry.lock"
      path: "$HOME/.cache/pypoetry/virtualenvs"
  steps:
    - step: &Install-step
        name: Smoke test
        caches:
            - pip
            - poetry
        script:
          - pip install -U pip
          - pip install --user pipx
          - export PATH="$HOME/.local/bin:$PATH"
          - pipx ensurepath
          - pipx install poetry
          - poetry install
          - source $(poetry env info --path)/bin/activate
          - pip install -e .
          - acli --help

pipelines:
  pull-requests:
    "refactoring/*":
      - step: *Install-step

  tags:
    "v*":
      - step: *Install-step
      - step:
          name: Push downstream
          script:
            - if [ "${SHOULD_PUSH_DOWNSTREAM}" != "true" ]; then printf "downstream push not enabled"; exit; fi
            - git pull -r $DOWNSTREAM_REPO $BITBUCKET_TAG || echo "tag $BITBUCKET_TAG does not exist"
            - git push $DOWNSTREAM_REPO $BITBUCKET_TAG || echo "tag $BITBUCKET_TAG already exists"

  branches:
    "refactoring/main":
      - step: *Install-step
      - step:
          name: Push downstream
          script:
            - if [ "${SHOULD_PUSH_DOWNSTREAM}" != "true" ]; then printf "downstream push not enabled"; exit; fi
            - git fetch $DOWNSTREAM_REPO main:github/main || echo "main branch does not exist"
            - git checkout refactoring/main
            - git rebase github/main || echo "errors rebasing to branch github/main"
            - git push $DOWNSTREAM_REPO refactoring/main:main
