[qoi]
resonator_spectroscopy_NCO.ro_freq = nan
resonator_spectroscopy_1_NCO.ro_freq_1 = nan
resonator_spectroscopy_2_NCO.ro_freq_2 = nan
SSRO.ro_freq_opt = nan
SSRO.ro_pulse_amp_opt = nan
qubit_01_spectroscopy_pulsed_NCO.freq_01 = nan
ramsey_correction_BATCHED.freq_01 = nan
qubit_12_spectroscopy_pulsed_NCO.freq_12 = nan
ramsey_correction_12_BATCHED.freq_12 = nan
qubit_12_spectroscopy_pulsed_NCO.anharmonicity = nan
rabi_oscillations_BATCHED.mw_amp180 = nan
DRAG_amplitude_BATCHED.mw_amp180 = nan
motzoi_parameter_BATCHED.mw_motzoi = nan
rabi_oscillations_12_BATCHED.mw_ef_amp180 = nan
randomized_benchmarking.fidelity = nan
SSRO_simple.discriminator = nan

[initials.all]
ro_acq_delay = 300e-9
ro_pulse_delay = 4e-9
ro_pulse_duration = 3.0e-6
ro_acq_integration_time = 2.5e-6
mw_pulse_duration = 48e-9
spec_pulse_duration = 4e-6
init_duration = 600e-6
min_calibration_point = 0
max_calibration_point = 0
att = 12

[initials]
q11.ro_pulse_amp = 3.5e-3
q12.ro_pulse_amp = 3.3e-3
q13.ro_pulse_amp = 1.3e-3
q14.ro_pulse_amp = 4.7e-3
q15.ro_pulse_amp = 3.0e-3
q16.ro_pulse_amp = 3.2e-3
q17.ro_pulse_amp = 2.3e-3
q18.ro_pulse_amp = 2.1e-3
q19.ro_pulse_amp = 3.6e-3
q20.ro_pulse_amp = 2.7e-3
q21.ro_pulse_amp = 2.3e-3
q22.ro_pulse_amp = 4.9e-3
q23.ro_pulse_amp = 4.0e-3
q24.ro_pulse_amp = 3.0e-3
q25.ro_pulse_amp = 4.0e-3

[resonator_spectroscopy_NCO.all]
init_duration = 100e-6

[resonator_spectroscopy_1_NCO.all]
init_duration = 100e-6

[resonator_spectroscopy_2_NCO.all]

init_duration = 100e-6

[qubit_01_spectroscopy_pulsed_NCO.all]
spec_pulse_amp = 2.0e-4

[qubit_12_spectroscopy_pulsed_NCO.all]
spec_pulse_amp = 2e-4
