[qoi]
resonator_spectroscopy.ro_freq = nan
resonator_spectroscopy_1.ro_freq_1 = nan
resonator_spectroscopy_2.ro_freq_2 = nan
SSRO.ro_freq_opt = nan
SSRO.ro_pulse_amp_opt = nan
qubit_01_spectroscopy_pulsed.freq_01 = nan
ramsey_correction.freq_01 = nan
qubit_12_spectroscopy_pulsed.freq_12 = nan
ramsey_correction_12.freq_12 = nan
qubit_12_spectroscopy_pulsed.anharmonicity = nan
rabi_oscillations.mw_amp180 = nan
DRAG_amplitude.mw_amp180 = nan
motzoi_parameter.mw_motzoi = nan
rabi_oscillations_12.mw_ef_amp180 = nan
randomized_benchmarking.fidelity = nan
SSRO_simple.discriminator = nan
XY_crosstalk.selectivity = nan

[initials.all]
ro_acq_delay = 200e-9
ro_pulse_delay = 4e-9
ro_pulse_duration = 3.0e-6
ro_acq_integration_time = 2.5e-6
mw_pulse_duration = 48e-9
spec_pulse_duration = 4e-6
init_duration = 600e-6
min_calibration_point = 0
max_calibration_point = 0
att = 0

[initials]
q11.ro_pulse_amp = 4.0e-3
q12.ro_pulse_amp = 4.3e-3
q13.ro_pulse_amp = 4.8e-3
q14.ro_pulse_amp = 5.5e-3
q15.ro_pulse_amp = 4.0e-3
q16.ro_pulse_amp = 4.2e-3
q17.ro_pulse_amp = 5.0e-3
q18.ro_pulse_amp = 4.1e-3
q19.ro_pulse_amp = 4.6e-3
q20.ro_pulse_amp = 4.2e-3
q21.ro_pulse_amp = 3.8e-3
q22.ro_pulse_amp = 5.7e-3
q23.ro_pulse_amp = 5.5e-3
q24.ro_pulse_amp = 4.5e-3
q25.ro_pulse_amp = 5.0e-3

[resonator_spectroscopy.all]
init_duration = 100e-6

[resonator_spectroscopy_1.all]
init_duration = 100e-6

[resonator_spectroscopy_2.all]
init_duration = 100e-6

[qubit_01_spectroscopy_pulsed.all]
mw_pulse_duration = 2e-6
mw_amp180 = 2.0e-4

[qubit_12_spectroscopy_pulsed.all]
spec_pulse_amp = 2e-4
