# This file is a configuration template for the initial values on each calibration run

#   --------------
#   Node reference
#   --------------
#
#   punchout
#   resonator_spectroscopy
#   qubit_01_spectroscopy
#   qubit_01_spectroscopy_pulsed
#   qubit_01_cw_spectroscopy
#   rabi_oscillations
#   ramsey_correction
#   resonator_spectroscopy_1
#   qubit_12_spectroscopy_pulsed
#   qubit_12_spectroscopy_multidim
#   rabi_oscillations_12
#   ramsey_correction_12
#   resonator_spectroscopy_2
#   ro_frequency_two_state_optimization
#   ro_frequency_three_state_optimization
#   ro_amplitude_two_state_optimization
#   ro_amplitude_three_state_optimization
#   coupler_spectroscopy
#   coupler_resonator_spectroscopy
#   motzoi_parameter
#   n_rabi_oscillations
#   randomized_benchmarking
#   state_discrimination
#   T1
#   T2
#   T2_echo
#   randomized_benchmarking
#   all_XY
#   check_cliffords
#   cz_chevron
#   cz_chevron_test
#   cz_chevron_amplitude
#   cz_optimize_chevron
#   reset_chevron
#   reset_calibration_ssro
#   cz_calibration
#   cz_calibration_ssro
#   cz_dynamic_phase
#   cz_dynamic_phase_swap
#   process_tomography_ssro
#   tqg_randomized_benchmarking
#   tqg_randomized_benchmarking_interleaved


[general]
target_node = "ro_amplitude_two_state_optimization"
qubits = ["q00"]
couplers = []

# This section contains initial values for all qubits
[initials.qubits.all]
measure.acq_delay = 200e-9
measure_1.acq_delay = 220e-9
measure_2.acq_delay = 220e-9
measure.pulse_duration = 2e-6
measure_1.pulse_duration = 3e-6
measure_2.pulse_duration = 3e-6
measure.integration_time = 1.5e-6
measure_1.integration_time = 2.5e-6
measure_2.integration_time = 2.5e-6
rxy.duration = 80e-9

# This section contains initial values for specific qubits

[initials.qubits]
q00.measure.pulse_amp = 0.2
q00.measure_1.pulse_amp = 0.01
q00.measure_2.pulse_amp = 0.01
q01.measure.pulse_amp = 0.2
q01.measure_1.pulse_amp = 0.01
q01.measure_2.pulse_amp = 0.01
reset.duration = 3000e-6

# This section contains initial values for all couplers
[initials.couplers.all]
cz_pulse_amplitude = 0.3
cz_pulse_width = 4e-9

# This section contains initial values for specific couplers
[initials.couplers]
q06_q07.parking_current = 0


# -------------------- Node configurations --------------------
# The follow sections contain initial values for specific nodes
[resonator_spectroscopy.all]
reset.duration =  60e-6

[punchout.all]
reset.duration =  60e-6

[resonator_spectroscopy_1.all]
reset.duration = 240e-6

[coupler_resonator_spectroscopy.all]
reset.duration = 100e-6

[resonator_spectroscopy_2.all]
reset.duration = 240e-6

[qubit_01_spectroscopy.all]
spec.spec_duration = 6e-6
reset.duration = 200e-6

[coupler_spectroscopy.all]
spec.spec_duration = 2e-6
# spec.spec_amp = 3.5e-4
reset.duration = 100e-6

[qubit_12_spectroscopy_pulsed.all]
spec.spec_duration = 2.0e-6
spec.spec_amp = 6e-4

[cz_chevron.all]
# cz_pulse_duration = 200e-9
coupler_spec_amp = 0.3

