project:
  render:
    - getting_started.qmd
    - operation.qmd
    - configuration_files.qmd
    - available_nodes.qmd
    - new_node_creation.qmd
    - node_types.qmd
    - unit_tests.qmd
  type: website
  output-dir: ../docs


website:
    title: 'Tergite Automatic Calibration'
    navbar:
      logo-href: getting_started.qmd
      left:
        - href: getting_started.qmd
        - href: operation.qmd
        - href: configuration_files.qmd
        - href: available_nodes.qmd
        - href: new_node_creation.qmd
          text: Creating New Nodes
        - href: node_types.qmd
        - href: unit_tests.qmd
          text: How to add unit tests

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
