project:
  type: website
  output-dir: ../docs


website:
  title: 'Tergite Automatic Calibration'
  navbar:
    logo-href: /
    left:
      - text: Home
        href: home.qmd
      - text: "User Guide"
        href: getting_started.qmd
      - text: "Node Library"
        href: available_nodes.qmd
      - text: "Developer Guide"
        href: developer-guide.qmd
    tools:
      - icon: github
        href: https://github.com/tergite/tergite-autocalibration
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "User Guide"
        contents:
          - text: "Getting started"
            href: getting_started.qmd
          - text: "Operation"
            href: user-guide/operation.qmd
          - text: "Configuration Files"
            href: user-guide/configuration_files.qmd
      - section: "Node Library"
        contents:
          - text: "Overview"
            href: available_nodes.qmd
          - text: "Resonator spectroscopy"
            href: nodes/resonator_spectroscopy_node.qmd
      - section: "Developer Guide"
        contents:
          - text: "Introduction"
            href: developer_guide.qmd
          - text: "Node Classes"
            href: developer-guide/node_classes.qmd
          - text: "Create a new node"
            href: developer-guide/new_node_creation.qmd
          - text: "Unit tests"
            href: developer-guide/unit_tests.qmd
  search:
    location: sidebar
    type: textbox

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toggle: true
    # css: styles.css - This is in case we were interested in having some custom modifications
    toc: true
