project:
  render:
    - getting_started.qmd
    - available_nodes.qmd
    - new_node_creation.qmd
    - node_types.qmd
  type: website
  output-dir: docs


website:
    title: 'Tergite Automatic Calibration'
    navbar:
      logo-href: getting_started.qmd
      left:
        - href: getting_started.qmd
        - href: available_nodes.qmd
        - href: new_node_creation.qmd
          text: Creating New Nodes
        - href: node_types.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
